
course: "CS190J"
course_main: "UCSB Teaching CS"
course_main_url: "https://ucsb-teaching-cs.github.io"
qtr: "F18"
quarter: "Fall 2018"
ta_list: ""
ta_list_full: ""
instructor: "Mirza,Conrad,Wang"
piazza: https://piazza.com/class/tbd

github_url: https://github.com/ucsb-cs190j-f18/ucsb-cs190j-f18.github.io
course_site: https://ucsb-cs190j-f18.github.io


start_week: 0
start_date: 2018-09-23 00:00:00.00-7:00
num_weeks: 11
extra_exam_week: true


cal_dates: >
  [
   {"label":"First day of instruction", "date":"2018-09-27" },
   {"label":"Univ Holiday", "date":"2018-11-12" },
   {"label":"Univ Holiday", "date":"2018-11-22" },
   {"label":"Univ Holiday", "date":"2018-11-23" },
   {"label":"Last day of instruction", "date":"2018-12-07" },
   {"label":"Finals Begin", "date":"2018-12-08" },
   {"label":"Finals End", "date":"2018-12-15" }
  ]

kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor

timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


